#!/usr/bin/env python3
"""Static-site builder for the Master Glass Solutions concept site.
All copy and page data live here so a future CMS/framework migration has one source of truth.
"""
from pathlib import Path
from html import escape
import json

OUT = Path(__file__).parent
SITE = "https://www.masterglasssolutionsusa.com"
PHONE_DISPLAY = "210-370-3700"
PHONE_LINK = "2103703700"
EMAIL = "contact@masterglasssolutionsusa.com"
ADDRESS = "108 Scheele Rd Unit 4, Boerne, TX 78015"

NAV = [
    ("Residential", "residential-glass.html"),
    ("Commercial", "commercial-glass.html"),
    ("Emergency", "emergency-glass-repair.html"),
    ("Service Areas", "service-areas.html"),
    ("Projects", "gallery.html"),
]

ICONS = {
    "arrow": "<svg aria-hidden=\"true\" viewBox=\"0 0 24 24\"><path d=\"M5 12h13M13 6l6 6-6 6\"/></svg>",
    "phone": "<svg aria-hidden=\"true\" viewBox=\"0 0 24 24\"><path d=\"M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6A19.79 19.79 0 0 1 2.12 4.18 2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13.96.37 1.9.7 2.81a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.91.33 1.85.57 2.81.7A2 2 0 0 1 22 16.92Z\"/></svg>",
    "check": "<svg aria-hidden=\"true\" viewBox=\"0 0 24 24\"><path d=\"m5 12 4 4L19 6\"/></svg>",
    "shield": "<svg aria-hidden=\"true\" viewBox=\"0 0 24 24\"><path d=\"M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z\"/><path d=\"m9 12 2 2 4-4\"/></svg>",
    "clock": "<svg aria-hidden=\"true\" viewBox=\"0 0 24 24\"><circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M12 7v5l3 2\"/></svg>",
    "measure": "<svg aria-hidden=\"true\" viewBox=\"0 0 24 24\"><path d=\"M3 21 21 3M5 5l14 14M4 10l3-3M9 15l3-3M14 20l3-3\"/></svg>",
    "map": "<svg aria-hidden=\"true\" viewBox=\"0 0 24 24\"><path d=\"M12 21s7-5.14 7-12A7 7 0 0 0 5 9c0 6.86 7 12 7 12Z\"/><circle cx=\"12\" cy=\"9\" r=\"2.5\"/></svg>",
}

def icon(name): return ICONS[name]

def slug_url(filename): return f"{SITE}/{filename.replace('.html','')}" if filename != "index.html" else SITE + "/"

def jsonld(data):
    return '<script type="application/ld+json">' + json.dumps(data, ensure_ascii=False) + '</script>'

def org_schema():
    return {
      "@context":"https://schema.org", "@type":"HomeAndConstructionBusiness", "@id": SITE + "/#business",
      "name":"Master Glass Solutions", "url":SITE + "/", "telephone":"+12103703700", "email":EMAIL,
      "image": SITE + "/assets/hero-storefront.jpg",
      "address":{"@type":"PostalAddress","streetAddress":"108 Scheele Rd Unit 4","addressLocality":"Boerne","addressRegion":"TX","postalCode":"78015","addressCountry":"US"},
      "areaServed":[{"@type":"City","name":"Boerne"},{"@type":"City","name":"San Antonio"}],
      "description":"Commercial and residential glass installation, fabrication, repair, storefront, shower enclosure and custom glass services in Boerne and San Antonio, Texas.",
      "knowsAbout":["Residential glass","Commercial glass","Emergency glass repair","Storefront glass","Custom glass","Shower enclosures","Mirrors","Window glass replacement"]
    }

def breadcrumb(items):
    list_items = [{"@type":"ListItem", "position":1, "name":"Home", "item":SITE + "/"}]
    for n, file in items:
        list_items.append({"@type":"ListItem", "position":len(list_items)+1,"name":n,"item":slug_url(file)})
    return {"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":list_items}

def service_schema(name, description, filename):
    return {"@context":"https://schema.org","@type":"Service","@id":slug_url(filename)+"#service", "name":name,
      "description":description, "url":slug_url(filename), "provider":{"@id":SITE+"/#business"},
      "areaServed":[{"@type":"City","name":"Boerne"},{"@type":"City","name":"San Antonio"}],
      "serviceType":name}

def faq_schema(faqs):
    return {"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":a}} for q,a in faqs]}

def page_schema(extra=None, crumbs=None, faqs=None):
    schemas=[org_schema()]
    if extra: schemas.append(extra)
    if crumbs: schemas.append(breadcrumb(crumbs))
    if faqs: schemas.append(faq_schema(faqs))
    return "\n".join(jsonld(x) for x in schemas)

def nav(active=""):
    links="".join(f'<a class="{ "active" if label==active else ""}" href="{href}">{label}</a>' for label,href in NAV)
    return f'''<a class="skip-link" href="#main">Skip to content</a>
<div class="utility"><div class="shell utility-inner"><span>{icon("clock")} 24/7 emergency glass support</span><a href="tel:{PHONE_LINK}">{icon("phone")} {PHONE_DISPLAY}</a></div></div>
<header class="site-header" data-header><div class="shell nav-wrap">
<a class="brand" href="index.html" aria-label="Master Glass Solutions home"><span class="brand-mark" aria-hidden="true"><i></i><i></i><i></i></span><span>MASTER <b>GLASS</b><em>SOLUTIONS</em></span></a>
<nav class="main-nav" aria-label="Primary navigation">{links}</nav>
<div class="nav-actions"><a class="nav-phone" href="tel:{PHONE_LINK}" aria-label="Call Master Glass Solutions">{icon("phone")}</a><a class="btn btn-small btn-dark" href="request-quote.html">Request a quote</a><button class="menu-toggle" type="button" aria-label="Open navigation" aria-expanded="false" data-menu-toggle><span></span><span></span></button></div>
</div><div class="mobile-nav" data-mobile-nav><div class="shell">{links}<a class="btn btn-dark" href="request-quote.html">Request a quote {icon("arrow")}</a><a class="mobile-call" href="tel:{PHONE_LINK}">{icon("phone")} Call {PHONE_DISPLAY}</a></div></div></header>'''

def footer():
    return f'''<footer class="site-footer"><div class="shell footer-grid">
<div class="footer-intro"><a class="brand brand-footer" href="index.html"><span class="brand-mark" aria-hidden="true"><i></i><i></i><i></i></span><span>MASTER <b>GLASS</b><em>SOLUTIONS</em></span></a><p>Commercial and residential glass work, fabricated and installed with a clear standard for precision.</p><a class="footer-phone" href="tel:{PHONE_LINK}">{icon("phone")} {PHONE_DISPLAY}</a></div>
<div><p class="footer-label">Explore</p><a href="residential-glass.html">Residential glass</a><a href="commercial-glass.html">Commercial glass</a><a href="storefront-glass.html">Storefront glass</a><a href="custom-glass.html">Custom glass</a></div>
<div><p class="footer-label">Resources & Guides</p><a href="resources.html">Resources center</a><a href="quote-process.html">Quote process guide</a><a href="glass-project-planning-checklist.html">Planning checklist</a><a href="gallery.html">Project showcase</a><a href="faq.html">FAQ</a><a href="thank-you.html" style="display:none;">Thank you</a></div>
<div><p class="footer-label">Visit / contact</p><address>{ADDRESS}</address><a href="mailto:{EMAIL}">{EMAIL}</a><a href="service-areas.html">Serving Boerne & San Antonio, TX</a></div>
</div><div class="shell footer-bottom"><span>© <span data-year></span> Master Glass Solutions. All rights reserved.</span><span>Powered by Chaotically Organized AI</span></div></footer>
<a class="mobile-call-fab" href="tel:{PHONE_LINK}" aria-label="Call Master Glass Solutions now">{icon("phone")}<span>Call now</span></a>'''

def glass_doors_overlay():
    return '''<div class="glass-doors-overlay" id="glassDoorsOverlay" aria-hidden="true">
<div class="glass-door glass-door-left"><div class="glass-door-glare"></div><div class="glass-door-handle"></div></div>
<div class="glass-door glass-door-right"><div class="glass-door-handle"></div><div class="glass-door-glare"></div></div>
<div class="glass-doors-brand"><span class="brand-mark"><i></i><i></i><i></i></span><span>MASTER <b>GLASS</b><em>SOLUTIONS</em></span></div>
</div>'''

def layout(title, description, filename, body, active="", crumbs=None, service=None, faqs=None, noindex=False):
    canonical=slug_url(filename)
    robot='<meta name="robots" content="noindex,follow">' if noindex else ''
    schema=page_schema(service, crumbs, faqs)
    return f'''<!doctype html>
<html lang="en-US"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>{escape(title)}</title><meta name="description" content="{escape(description)}"><link rel="canonical" href="{canonical}">
<meta property="og:type" content="website"><meta property="og:title" content="{escape(title)}"><meta property="og:description" content="{escape(description)}"><meta property="og:url" content="{canonical}"><meta property="og:image" content="{SITE}/assets/hero-storefront.jpg"><meta name="twitter:card" content="summary_large_image">{robot}
<link rel="stylesheet" href="assets/styles.css">{schema}</head>
<body>{glass_doors_overlay()}{nav(active)}<main id="main">{body}</main>{footer()}<script src="assets/scripts.js" defer></script><script>window.va=window.va||function(){{(window.vaq=window.vaq||[]).push(arguments)}};</script><script defer src="https://cdn.vercel-insights.com/v1/script.js"></script></body></html>'''

def eyebrow(txt): return f'<p class="eyebrow"><span></span>{txt}</p>'
def cta_quote(label="Request a quote", cls="btn btn-light"): return f'<a class="{cls}" href="request-quote.html">{label} {icon("arrow")}</a>'
def cta_call(label="Call {PHONE_DISPLAY}", cls="btn btn-ghost"): return f'<a class="{cls}" href="tel:{PHONE_LINK}">{icon("phone")} {label}</a>'

def inner_hero(eyebrow_text, h1, intro, image="hero-storefront.jpg", actions=None):
    if not actions: actions=cta_quote()+cta_call()
    return f'''<section class="inner-hero"><div class="inner-hero-image" style="background-image:linear-gradient(90deg,rgba(9,22,31,.93) 0%,rgba(9,22,31,.76) 46%,rgba(9,22,31,.2) 100%),url('assets/{image}')"></div><div class="shell inner-hero-content">{eyebrow(eyebrow_text)}<h1>{h1}</h1><p>{intro}</p><div class="hero-actions">{actions}</div></div></section>'''

def trust_strip():
    return f'''<section class="trust-strip"><div class="shell trust-grid"><div>{icon("measure")}<span><b>20+ years</b> of experience</span></div><div>{icon("shield")}<span><b>Commercial + residential</b> glass expertise</span></div><div>{icon("clock")}<span><b>24/7 support</b> for urgent glass needs</span></div><div>{icon("map")}<span><b>Boerne + San Antonio</b> local focus</span></div></div></section>'''

def faq_section(faqs, title="Clear answers, before you commit", intro=None):
    intro_html=f'<p class="section-intro">{intro}</p>' if intro else ''
    items="".join(f'''<details><summary>{q}<span>+</span></summary><div class="faq-answer"><p>{a}</p></div></details>''' for q,a in faqs)
    return f'''<section class="section faq-section"><div class="shell faq-layout"><div>{eyebrow("FAQ")}<h2>{title}</h2>{intro_html}<a class="text-link" href="faq.html">See every question {icon("arrow")}</a></div><div class="faq-list">{items}</div></div></section>'''

def mini_cta(title="A precise next step starts with a clear conversation.", text="Tell us what you’re planning, repairing, or replacing. We’ll help you identify the right path.", urgent=False):
    primary = f'<a class="btn btn-alert" href="tel:{PHONE_LINK}">{icon("phone")} Call emergency support</a>' if urgent else cta_quote("Start your quote", "btn btn-light")
    secondary = cta_quote("Request a project estimate", "btn btn-ghost") if urgent else cta_call()
    return f'''<section class="section final-cta"><div class="final-rule"></div><div class="shell final-cta-grid"><div>{eyebrow("MASTER GLASS SOLUTIONS")}<h2>{title}</h2></div><div><p>{text}</p><div class="hero-actions">{primary}{secondary}</div></div></div></section>'''

HOME_FAQS = [
 ("What glass services does Master Glass Solutions provide?", "Master Glass Solutions provides commercial and residential glass installation and fabrication, including storefront glass, emergency glass repair, custom glass, shower enclosures, mirrors, and window glass replacement in Boerne and San Antonio."),
 ("Do you offer emergency glass repair?", "Yes. Emergency glass support is available 24/7 for urgent broken glass situations. Call 210-370-3700 so the team can understand the opening, safety concern, and next step."),
 ("Do you work on both homes and commercial properties?", "Yes. The team serves residential and commercial projects, from custom home glass and shower enclosures to storefronts, partitions, repair, and project-specific fabrication."),
 ("How do I request a glass estimate?", "Call 210-370-3700 or use the quote form. The most helpful starting details are the property location, the type of glass work, approximate dimensions or photos if available, and your desired timing."),
]

def home():
    return f'''<section class="hero-home"><div class="hero-image" role="img" aria-label="Premium commercial glass storefront at blue hour"></div><div class="hero-scrim"></div><div class="shell hero-grid"><div class="hero-copy">{eyebrow("BOERNE + SAN ANTONIO  •  COMMERCIAL & RESIDENTIAL GLASS")}<h1>Glass work that makes the whole property feel finished.</h1><p>Thoughtfully fabricated. Precisely installed. Master Glass Solutions brings more than 20 years of experience to glass projects that demand a clean line, a confident fit, and dependable service.</p><div class="hero-actions">{cta_quote("Request a quote", "btn btn-light")}{cta_call("Emergency? Call now", "btn btn-ghost")}</div><p class="hero-note">For planned projects and urgent glass needs.</p></div><aside class="hero-panel" aria-label="Glass service options"><p>What brings you here?</p><a href="residential-quote.html"><span>Residential glass</span>{icon("arrow")}</a><a href="commercial-quote.html"><span>Commercial project</span>{icon("arrow")}</a><a href="emergency.html"><span>Broken glass emergency</span>{icon("arrow")}</a></aside></div></section>
{trust_strip()}
<section class="section introduction"><div class="shell intro-grid"><div class="intro-statement"><p class="numbered">01</p>{eyebrow("THE RIGHT GLASS CHANGES THE ROOM")}<h2>Built around the opening. Guided by the details.</h2></div><div class="intro-copy"><p class="lead">Glass does more than fill a frame. It shapes first impressions, protects what matters, opens a view, and makes a space feel intentional.</p><p>Master Glass Solutions pairs project-minded planning with the hands-on precision of skilled glass installation and fabrication. Whether you are refreshing a home, maintaining a property, or building out a business, the work starts by understanding the job—not forcing it into a one-size-fits-all answer.</p><a class="text-link" href="about.html">Meet the standard behind the work {icon("arrow")}</a></div></div></section>
<section class="section section-ink paths"><div class="shell"><div class="section-heading split-heading">{eyebrow("START WITH YOUR PROJECT")}<div><h2>Different properties. One exacting standard.</h2><p>Choose the path that fits your project and get to the conversation that matters faster.</p></div></div><div class="path-grid"><a class="path-card path-residential" href="residential-glass.html"><div><p class="card-kicker">FOR THE HOME</p><h3>Residential<br>glass</h3><p>Shower enclosures, mirrors, window glass replacement, and custom details that elevate everyday spaces.</p></div><span class="circle-arrow">{icon("arrow")}</span></a><a class="path-card path-commercial" href="commercial-glass.html"><div><p class="card-kicker">FOR THE BUSINESS</p><h3>Commercial<br>glass</h3><p>Storefronts, partitions, repair, and project-built glass work for properties that need to perform.</p></div><span class="circle-arrow">{icon("arrow")}</span></a></div></div></section>
<section class="section services-section"><div class="shell"><div class="section-heading">{eyebrow("WHAT WE DO")}<h2>From first impression to final detail.</h2><p>Focused services make it easier to find the right answer—and easier for search engines and AI assistants to understand exactly how we help.</p></div><div class="service-grid">
{service_card("Residential glass", "Custom glass that brings light, function, and a finished feel to the home.", "residential-glass.html", "01")}
{service_card("Commercial glass", "Professional glass solutions for offices, retail spaces, properties, and build-outs.", "commercial-glass.html", "02")}
{service_card("Emergency glass repair", "24/7 support when broken glass creates an immediate safety or security concern.", "emergency-glass-repair.html", "03")}
{service_card("Storefront glass", "Glass systems designed to welcome customers while supporting the demands of daily business.", "storefront-glass.html", "04")}
{service_card("Custom glass", "Purpose-built solutions for spaces that deserve more than an off-the-shelf fit.", "custom-glass.html", "05")}
{service_card("Window glass replacement", "Clearer, safer, better-performing glass for existing residential window openings.", "window-glass-replacement.html", "06")}
</div></div></section>
<section class="section craftsmanship"><div class="shell craft-grid"><div class="craft-image image-commercial" role="img" aria-label="Modern office with custom glass partitions"></div><div class="craft-content">{eyebrow("WHY MASTER GLASS SOLUTIONS")}<h2>Precision is visible. So is the lack of it.</h2><p>Clean reveals. Thoughtful proportions. Hardware that sits right. A glass project earns its place when the finished result feels quietly inevitable.</p><ul class="check-list"><li>{icon("check")}A clear path from project conversation to installation</li><li>{icon("check")}Experience across both commercial and residential glass needs</li><li>{icon("check")}Fabrication and installation built around the specific opening</li><li>{icon("check")}24/7 support when glass damage cannot wait</li></ul><a class="text-link" href="custom-glass.html">Explore custom glass solutions {icon("arrow")}</a></div></div></section>
<section class="section process"><div class="shell"><div class="section-heading centered">{eyebrow("HOW IT WORKS")}<h2>A simple process, with the details handled properly.</h2><p>Answer-first: Tell us what you need. We clarify the scope. Then we move toward a precise installation or repair plan.</p></div><ol class="process-grid"><li><span>01</span><h3>Start with the opening</h3><p>Share the project type, location, timing, and any photos or dimensions you have.</p></li><li><span>02</span><h3>Clarify the scope</h3><p>We help identify the glass service, requirements, and practical next steps.</p></li><li><span>03</span><h3>Build the right plan</h3><p>For planned work, the project is shaped around the actual space—not assumptions.</p></li><li><span>04</span><h3>Finish with intent</h3><p>Installation and final details are approached with care for the property and the result.</p></li></ol></div></section>
<section class="project-strip"><div class="project-strip-image shower" role="img" aria-label="Custom frameless glass shower enclosure"></div><div class="project-strip-copy"><p class="card-kicker">PROJECT SHOWCASE</p><h2>Details that keep the space feeling considered.</h2><p>Explore glass applications for homes and commercial environments—then bring your own project into focus.</p><a class="btn btn-dark" href="gallery.html">View the project showcase {icon("arrow")}</a><small>Concept imagery shown in this prototype. Publish real Master Glass project photography for proof.</small></div></section>
<section class="emergency-band"><div class="shell emergency-grid"><div><p class="eyebrow"><span></span>24/7 EMERGENCY GLASS SUPPORT</p><h2>Broken glass is not a “tomorrow” problem.</h2><p>For a damaged storefront, window, or glass opening that needs attention, call now. Start with the safety and security of the property.</p></div><div class="emergency-actions"><a href="tel:{PHONE_LINK}" class="emergency-phone">{icon("phone")} <span>Call for urgent glass support<strong>{PHONE_DISPLAY}</strong></span></a><a class="text-link light-link" href="emergency-glass-repair.html">What to do next {icon("arrow")}</a></div></div></section>
<section class="section proof-section"><div class="shell proof-layout"><div>{eyebrow("TRUST IS EARNED IN THE DETAILS")}<h2>Let verified feedback do the talking.</h2><p>A high-trust site should display a live, permissioned feed of Google reviews and approved client feedback—not invented quotes. Connect the verified review source here before launch, then feature the most specific feedback about communication, workmanship, and responsiveness.</p><a class="text-link" href="reviews.html">See our review standards {icon("arrow")}</a></div><div class="proof-cards"><article><span class="proof-symbol">“</span><p class="placeholder-label">Verified-review module</p><h3>Show real client words, source, and rating.</h3><p>Use only published Google reviews or written permissions. Never fabricate social proof.</p></article><article><span class="proof-number">20<span>+</span></span><h3>Years of experience</h3><p>Use the team’s stated experience as a grounded signal—then let clear project information support it.</p></article></div></div></section>
{faq_section(HOME_FAQS, "Questions homeowners and property teams ask first.", "Short, direct answers help customers make a decision and give AI search systems clear facts to quote.")}
{mini_cta("Your next glass project deserves a clear answer.", "Call for urgent needs or request a quote for a planned residential or commercial project in Boerne or San Antonio.")}
'''

def service_card(title,text,href,num):
    return f'''<a class="service-card" href="{href}"><span class="service-number">{num}</span><div><h3>{title}</h3><p>{text}</p></div><span class="service-arrow">{icon("arrow")}</span></a>'''

SERVICE_DATA = {
"residential-glass.html": {
 "nav":"Residential", "name":"Residential Glass", "short":"Residential glass installation and custom glass solutions for homes in Boerne and San Antonio, Texas.",
 "title":"Residential Glass in Boerne & San Antonio, TX | Master Glass Solutions", "h1":"Residential glass with a finished, considered feel.", "eyebrow":"RESIDENTIAL GLASS • BOERNE + SAN ANTONIO", "image":"residential-shower.jpg",
 "intro":"From a clean-lined shower enclosure to a replacement glass pane or a custom mirror, the details inside a home deserve a glass solution that looks right and functions well.",
 "needs":["You are updating a bathroom with a frameless or custom shower enclosure.","A broken, fogged, or damaged window pane needs evaluation or replacement.","You need a custom mirror or a piece of glass made for a specific space.","You want a clear plan before a renovation, remodel, or finishing detail moves forward."],
 "services":[("Shower enclosures","Frameless and custom shower glass concepts shaped around the room.","shower-enclosures.html"),("Mirrors","Custom-cut mirrors that bring dimension and function to a space.","mirrors.html"),("Window glass replacement","A focused solution for damaged or failed glass in existing window openings.","window-glass-replacement.html"),("Custom glass","Glass solutions that need a made-for-the-space approach.","custom-glass.html")],
 "cost":"Scope, glass type and thickness, opening size, hardware, access, fabrication, and the condition of the existing opening all influence a residential glass estimate.",
 "faqs":[("What types of residential glass work do you provide?","Residential services include custom shower enclosures, mirrors, window glass replacement, custom glass, and other home glass installation needs."),("Can you help with a custom shower enclosure?","Yes. Share photos, approximate dimensions, the design direction, and timing. The project should be evaluated around the actual shower opening and hardware needs."),("What should I send for a residential glass quote?","Start with the property location, service type, photos, rough dimensions if known, and desired timing. The more context you share, the easier it is to guide the next step.")]
},
"commercial-glass.html": {
 "nav":"Commercial", "name":"Commercial Glass", "short":"Commercial glass installation, fabrication and repair for businesses and properties in Boerne and San Antonio, Texas.",
 "title":"Commercial Glass in Boerne & San Antonio, TX | Master Glass Solutions", "h1":"Commercial glass that carries the standard of the business behind it.", "eyebrow":"COMMERCIAL GLASS • BOERNE + SAN ANTONIO", "image":"commercial-interior.jpg",
 "intro":"From the first view through a storefront to the function of an interior partition, commercial glass needs to look composed, fit the operational reality, and support the property without unnecessary friction.",
 "needs":["You are planning a storefront, office, retail, or tenant-improvement project.","An existing commercial glass opening needs repair, replacement, or a clearer plan.","You need interior glass partitions or a project-specific glass feature.","Your property has urgent glass damage that affects safety, security, or operations."],
 "services":[("Storefront glass","Glass systems and repair paths for customer-facing business openings.","storefront-glass.html"),("Emergency glass repair","24/7 support for urgent damaged-glass situations.","emergency-glass-repair.html"),("Custom commercial glass","Purpose-built details and glass applications for the space at hand.","custom-glass.html"),("Commercial project estimate","A focused entry point for project stakeholders and property teams.","commercial-quote.html")],
 "cost":"Commercial estimates depend on scope, system and glass specifications, dimensions, access, fabrication, existing conditions, scheduling, and any project-specific requirements.",
 "faqs":[("What commercial glass services do you offer?","Master Glass Solutions provides commercial glass installation and fabrication, storefront glass, interior glass applications, emergency repair support, and custom glass solutions."),("Do you work with property managers and project teams?","The commercial quote path is designed to collect the project details a property manager, business owner, contractor, or project team can provide so the right next conversation can happen."),("What should a commercial estimate request include?","Include the property address, project type, timeline, decision-maker contact, relevant plans or photos, approximate dimensions if known, and any access or site constraints.")]
},
"emergency-glass-repair.html": {
 "nav":"Emergency", "name":"Emergency Glass Repair", "short":"24/7 emergency glass support for urgent broken glass needs in Boerne and San Antonio, Texas.",
 "title":"24/7 Emergency Glass Repair in Boerne & San Antonio, TX | Master Glass Solutions", "h1":"When glass breaks, start with a calm, clear next step.", "eyebrow":"24/7 EMERGENCY GLASS SUPPORT • BOERNE + SAN ANTONIO", "image":"emergency-glass.jpg",
 "intro":"Broken glass can create an immediate safety, security, weather, and business-continuity concern. Call Master Glass Solutions for 24/7 emergency support and explain what happened, where it is, and whether the opening is currently secure.",
 "needs":["A storefront window or door glass is broken or compromised.","A home window or glass opening has been damaged and poses a safety or security concern.","A glass opening is exposed after hours, during weather, or while a business is operating.","You need help determining the immediate next step for an urgent glass situation."],
 "services":[("Commercial emergency glass","Urgent glass support for storefronts and commercial openings.","storefront-glass.html"),("Residential glass repair path","A clear route for a home glass issue that needs assessment.","residential-glass.html"),("Window glass replacement","Planned replacement information for existing residential window glass.","window-glass-replacement.html")],
 "cost":"Emergency glass repair costs vary with the opening, glass type, time-sensitive conditions, temporary securing needs, access, dimensions, and the final replacement scope. Call to discuss the immediate situation.",
 "faqs":[("Do you offer 24/7 emergency glass repair?","Yes. Master Glass Solutions states 24/7 support for emergency glass needs. Call 210-370-3700 to explain the situation and location."),("What should I do first after glass breaks?","Keep people away from loose glass, avoid touching damaged edges, protect the area if it can be done safely, and call for support. If there is an immediate danger or emergency, contact local emergency services first."),("Can you help with a broken storefront window?","Storefront damage is an appropriate reason to call the emergency support line. Explain the type of opening, property location, whether it is secure, and any immediate safety concern.")]
},
"storefront-glass.html": {
 "nav":"Commercial", "name":"Storefront Glass", "short":"Storefront glass installation, replacement and repair for Boerne and San Antonio businesses.",
 "title":"Storefront Glass in Boerne & San Antonio, TX | Master Glass Solutions", "h1":"Storefront glass that welcomes customers—and supports the work inside.", "eyebrow":"STOREFRONT GLASS • BOERNE + SAN ANTONIO", "image":"hero-storefront.jpg",
 "intro":"The storefront is part of the business experience. It needs to feel clean, visible, and appropriate to the building while supporting the realities of a busy commercial property.",
 "needs":["You are planning a new or updated customer-facing glass opening.","A storefront pane, door glass, or related opening needs replacement or repair.","You need to coordinate a glass scope for a business, retail, or property project.","Damaged storefront glass has created an urgent security or safety problem."],
 "services":[("Commercial glass","Explore broader commercial installation and fabrication needs.","commercial-glass.html"),("Emergency glass repair","A direct line for urgent glass damage.","emergency-glass-repair.html"),("Commercial estimate","Send property and project details through a focused estimate form.","commercial-quote.html")],
 "cost":"Storefront glass cost is shaped by the opening size, glass and system specifications, framing condition, access, replacement or new-install scope, and any urgent securing requirements.",
 "faqs":[("What is storefront glass?","Storefront glass refers to the customer-facing glazed systems at a commercial building, often including windows, entrances, and related framing components."),("Do you provide emergency storefront glass support?","Yes. Call 210-370-3700 for 24/7 emergency glass support when storefront damage needs urgent attention."),("How do I request a storefront glass estimate?","Send the property address, photos, rough dimensions if available, a description of the opening, timing, and the best decision-maker contact.")]
},
"custom-glass.html": {
 "nav":"Residential", "name":"Custom Glass", "short":"Custom glass fabrication and installation for residential and commercial spaces in Boerne and San Antonio, Texas.",
 "title":"Custom Glass in Boerne & San Antonio, TX | Master Glass Solutions", "h1":"Custom glass, considered at the level of the space.", "eyebrow":"CUSTOM GLASS • BOERNE + SAN ANTONIO", "image":"residential-shower.jpg",
 "intro":"The right custom glass solution should feel integrated—not added on. Start with the purpose of the opening, the materials around it, and the exact visual or functional need the finished piece must meet.",
 "needs":["A standard product will not suit the dimensions or design of the space.","You need a glass detail that works with a remodel, specialty opening, or commercial application.","A mirror, partition, enclosure, or feature needs a made-for-the-space approach.","You want help framing a glass idea before fabrication and installation decisions are made."],
 "services":[("Residential glass","Custom options for a home project, renovation, or finishing detail.","residential-glass.html"),("Commercial glass","Custom glass application paths for business and property projects.","commercial-glass.html"),("Shower enclosures","Explore a focused custom shower glass route.","shower-enclosures.html"),("Mirrors","Explore mirror installation and custom sizing.","mirrors.html")],
 "cost":"Custom glass pricing depends on the final dimensions, glass selection, edge and finish details, hardware or support requirements, fabrication complexity, installation access, and quantity.",
 "faqs":[("What does custom glass mean?","Custom glass is fabricated and selected around the needs of a specific opening, use case, dimension, or design detail rather than being treated as a standard off-the-shelf fit."),("Can custom glass be used in homes and businesses?","Yes. Custom glass can be relevant to both residential and commercial settings when the space, opening, design, or function needs a project-specific approach."),("What information helps with a custom glass request?","Photos, approximate dimensions, project location, desired use, material references, timing, and a short description of the result you want all help start the conversation.")]
},
"shower-enclosures.html": {
 "nav":"Residential", "name":"Shower Enclosures", "short":"Custom and frameless shower enclosure solutions for homes in Boerne and San Antonio, Texas.",
 "title":"Shower Enclosures in Boerne & San Antonio, TX | Master Glass Solutions", "h1":"A shower enclosure should feel open, aligned, and made for the room.", "eyebrow":"SHOWER ENCLOSURES • BOERNE + SAN ANTONIO", "image":"residential-shower.jpg",
 "intro":"Frameless and custom shower glass can give a bathroom a cleaner visual line and a more intentional finish. The right approach begins with the actual tile, walls, layout, and daily use of the shower.",
 "needs":["You are remodeling a bathroom and want a glass enclosure that complements the space.","You need an existing shower glass door or enclosure evaluated for replacement.","You want a clean, more open alternative to a standard shower surround.","Your project needs glass and hardware decisions shaped around the finished bathroom."],
 "services":[("Residential glass","See the wider range of home glass solutions.","residential-glass.html"),("Custom glass","For details that need to fit a one-of-one space.","custom-glass.html"),("Mirrors","Pair a shower renovation with a considered mirror solution.","mirrors.html")],
 "cost":"Shower enclosure estimates are shaped by the layout, glass dimensions and thickness, door configuration, hardware, tile and wall conditions, number of panels, and installation access.",
 "faqs":[("What is a frameless shower enclosure?","A frameless shower enclosure uses heavy glass and minimal visible framing to create a clean, open visual effect. The correct configuration depends on the room and opening."),("What do I need before requesting a shower glass quote?","Send photos of the shower, rough dimensions if available, your desired door or panel style, property location, and the stage of the remodel."),("Can you help with a custom shower glass layout?","Yes. A custom shower enclosure path is appropriate when the opening, design, or hardware needs to be considered around the room.")]
},
"mirrors.html": {
 "nav":"Residential", "name":"Custom Mirrors", "short":"Custom mirror fabrication and installation for homes and commercial spaces in Boerne and San Antonio, Texas.",
 "title":"Custom Mirrors in Boerne & San Antonio, TX | Master Glass Solutions", "h1":"Mirrors that give the room more light, depth, and intention.", "eyebrow":"CUSTOM MIRRORS • BOERNE + SAN ANTONIO", "image":"residential-shower.jpg",
 "intro":"A well-proportioned mirror changes more than a wall. It can extend light, sharpen a bathroom or vanity, and finish a commercial or residential room with a simple, useful detail.",
 "needs":["You need a custom mirror for a bath, vanity, hallway, gym, studio, or feature wall.","A mirror needs replacement after damage or a renovation.","The size, shape, edge treatment, or installation situation calls for a tailored solution.","You want to coordinate a mirror with a larger glass or renovation project."],
 "services":[("Residential glass","Explore more home glass installation services.","residential-glass.html"),("Custom glass","For glass and mirror requirements that are specific to the space.","custom-glass.html"),("Shower enclosures","Coordinate a bath mirror and shower glass project.","shower-enclosures.html")],
 "cost":"Mirror pricing depends on dimensions, mirror type, edge or finish details, number of pieces, mounting approach, wall conditions, access, and installation complexity.",
 "faqs":[("Can you make a mirror for a specific wall or vanity?","A custom mirror request is designed for spaces where dimensions and finished details need to be considered around the actual location."),("What information helps with a mirror quote?","Share the wall or installation location, rough dimensions, photos, desired mirror style or edge detail, timing, and the property address."),("Can mirrors be part of a larger bathroom project?","Yes. Mirrors can be planned alongside a shower enclosure or other residential glass work so the details feel coordinated.")]
},
"window-glass-replacement.html": {
 "nav":"Residential", "name":"Window Glass Replacement", "short":"Residential window glass replacement and repair guidance for Boerne and San Antonio, Texas.",
 "title":"Window Glass Replacement in Boerne & San Antonio, TX | Master Glass Solutions", "h1":"When the pane is the problem, start with the right glass answer.", "eyebrow":"WINDOW GLASS REPLACEMENT • BOERNE + SAN ANTONIO", "image":"hero-storefront.jpg",
 "intro":"Damaged, broken, or failed glass can affect the look, comfort, safety, and day-to-day performance of a window. The next step is to understand the window, the glass condition, and the scope of replacement needed.",
 "needs":["A window pane is broken, cracked, damaged, or otherwise compromised.","You have noticed signs that the glass itself may need evaluation or replacement.","You need help understanding the glass component of an existing window opening.","The damage creates an urgent safety or security concern and cannot wait."],
 "services":[("Emergency glass repair","Call the 24/7 line when damage is urgent.","emergency-glass-repair.html"),("Residential glass","Explore broader home glass services.","residential-glass.html"),("Custom glass","For a project-specific glass requirement.","custom-glass.html")],
 "cost":"Window glass replacement cost depends on the pane size, glass configuration, existing window condition, access, safety requirements, labor complexity, and whether temporary securing is needed.",
 "faqs":[("Can a broken window pane be replaced?","Many situations begin with evaluating the glass pane, opening, and existing window condition. Share photos and details so the correct next step can be discussed."),("What should I do if a window is broken now?","Keep people away from broken glass and contact 24/7 emergency support at 210-370-3700 if the condition is urgent or creates a safety or security concern."),("What information helps with window glass replacement?","Provide photos, the window location, rough pane dimensions, an explanation of the damage, property address, and timing.")]
}
}

def service_page(filename, d):
    cards="".join(f'''<a class="related-service" href="{href}"><h3>{name}</h3><p>{desc}</p><span>{icon("arrow")}</span></a>''' for name,desc,href in d["services"])
    needs="".join(f'<li>{icon("check")}{x}</li>' for x in d["needs"])
    body=f'''{inner_hero(d["eyebrow"],d["h1"],d["intro"],d["image"])}
{trust_strip()}
<section class="section answer-section"><div class="shell answer-grid"><div>{eyebrow("AT A GLANCE")}<h2>What is {d["name"].lower()}?</h2></div><div><p class="lead">{d["short"]}</p><p>This service page is organized to answer the practical questions a homeowner, business owner, property manager, or project team asks before making contact: when the service is relevant, how the process starts, what shapes cost, and what to expect next.</p><a class="text-link" href="request-quote.html">Tell us about your project {icon("arrow")}</a></div></div></section>
<section class="section section-cream"><div class="shell split-info"><div class="when-block">{eyebrow("WHEN YOU MAY NEED THIS")}<h2>Start here when…</h2><ul class="check-list">{needs}</ul></div><div class="how-block">{eyebrow("HOW IT WORKS")}<h2>A clearer next step.</h2><ol class="compact-steps"><li><span>01</span><div><h3>Share the essentials</h3><p>Tell us the location, glass need, timing, and what you can see from photos or plans.</p></div></li><li><span>02</span><div><h3>Align on the scope</h3><p>The right conversation starts by separating the immediate issue from the finished result.</p></div></li><li><span>03</span><div><h3>Move with intention</h3><p>Use the estimate or emergency path that fits the property and the urgency of the situation.</p></div></li></ol></div></div></section>
<section class="section related-section"><div class="shell"><div class="section-heading split-heading">{eyebrow("RELATED GLASS SERVICES")}<div><h2>The right answer may be part of a bigger scope.</h2><p>Explore the focused service page that matches the actual opening, property, or project situation.</p></div></div><div class="related-grid">{cards}</div></div></section>
<section class="section cost-section"><div class="shell cost-grid"><div><p class="numbered">COST</p>{eyebrow("ESTIMATE CONTEXT")}<h2>What influences the investment?</h2></div><div><p class="lead">{d["cost"]}</p><p>For a useful conversation, share as much context as you have. A photo, rough measurement, address, and project timeline are often more valuable than trying to guess the solution first.</p>{cta_quote("Request a tailored quote", "btn btn-dark")}</div></div></section>
{faq_section(d["faqs"], "Service questions, answered directly.", "These answers provide a fast starting point. For a project-specific recommendation, call or send the details of your opening.")}
{mini_cta(f"Let’s bring clarity to your {d['name'].lower()} project.", "Request a quote for planned work, or call immediately if the situation is urgent.", filename=="emergency-glass-repair.html")}
'''
    return layout(d["title"],d["short"],filename,body,d["nav"],[(d["name"],filename)],service_schema(d["name"],d["short"],filename),d["faqs"])

def quote_form(kind="General project"):
    options = "".join(f'<option>{x}</option>' for x in ["Residential glass","Commercial glass","Emergency glass repair","Storefront glass","Custom glass","Shower enclosure","Mirror","Window glass replacement","Not sure yet"])
    selected = {"General project":"", "Residential project":"Residential glass", "Commercial project":"Commercial glass"}.get(kind, "")
    op="".join(f'<option value="{x}" {"selected" if x==selected else ""}>{x}</option>' for x in ["","Residential glass","Commercial glass","Emergency glass repair","Storefront glass","Custom glass","Shower enclosure","Mirror","Window glass replacement","Not sure yet"])
    business = '<label>Business / property name <input name="business" autocomplete="organization"></label>' if kind=="Commercial project" else ''
    return f'''<form class="lead-form" action="thank-you.html" method="get" data-lead-form><div class="form-title"><span>01</span><div><h2>Project details</h2><p>Fields marked <b>*</b> help us route your request.</p></div></div><div class="form-grid"><label>First name <b>*</b><input required name="first-name" autocomplete="given-name"></label><label>Last name <b>*</b><input required name="last-name" autocomplete="family-name"></label><label>Email <b>*</b><input required type="email" name="email" autocomplete="email"></label><label>Phone <b>*</b><input required type="tel" name="phone" inputmode="tel" autocomplete="tel"></label>{business}<label>Service needed <b>*</b><select required name="service">{op}</select></label><label>Property address / city <b>*</b><input required name="location" autocomplete="street-address" placeholder="e.g., Boerne, TX"></label><label>Desired timing <select name="timeline"><option>As soon as possible</option><option>Within 2 weeks</option><option>Within 30 days</option><option>Planning / gathering information</option></select></label><label class="full">Tell us about the opening or project <b>*</b><textarea required name="details" rows="5" placeholder="Photos, rough dimensions, project type, and anything that would help us understand the work."></textarea></label><label class="checkbox full"><input required type="checkbox" name="consent"><span>I agree that Master Glass Solutions may contact me about this request. <b>*</b></span></label></div><button class="btn btn-dark form-submit" type="submit">Send my project request {icon("arrow")}</button><p class="form-note">Before launch: connect this secure form to the business CRM/inbox and publish the privacy policy. Do not route emergency requests through this form.</p></form>'''

def quote_page(filename, kind, h1, intro, eyebrow_text, emergency=False):
    side = f'''<div class="quote-side"><div>{eyebrow("WHAT HAPPENS NEXT")}<h2>A clear handoff starts with the right details.</h2><ol class="quote-steps"><li><span>01</span><p>Your request is organized by service, location, and timing.</p></li><li><span>02</span><p>The right contact gets the project context needed for the next conversation.</p></li><li><span>03</span><p>You move forward with a more precise understanding of the scope.</p></li></ol></div><div class="aside-contact"><p>Need immediate glass support?</p><a href="tel:{PHONE_LINK}">{icon("phone")} {PHONE_DISPLAY}</a><small>24/7 emergency support</small></div></div>'''
    body=f'''{inner_hero(eyebrow_text,h1,intro,"hero-storefront.jpg",cta_call("Call for emergency support", "btn btn-alert") if emergency else cta_call())}
<section class="section quote-page"><div class="shell quote-layout">{quote_form(kind)}{side}</div></section>'''
    return layout(f"{h1} | Master Glass Solutions",intro,filename,body,"",[("Request a Quote",filename)],None,None,filename=="thank-you.html")

def about_page():
    faqs=[("Where is Master Glass Solutions located?",f"Master Glass Solutions is located at {ADDRESS}."),("Which areas do you serve?","The current local focus is Boerne and San Antonio, Texas. Contact the team with the property location to discuss a specific project."),("What experience does the team bring?","Master Glass Solutions states more than 20 years of experience in commercial and residential glass installation and fabrication.")]
    body=f'''{inner_hero("ABOUT MASTER GLASS SOLUTIONS","A clear standard for work people see every day.","Master Glass Solutions is a commercial and residential glass installation and fabrication company serving the Boerne and San Antonio area. The work is built around precision, reliable service, and craftsmanship that belongs in the finished space.","commercial-interior.jpg")}
{trust_strip()}
<section class="section story"><div class="shell story-grid"><div>{eyebrow("OUR APPROACH")}<h2>The project is specific. The standard should be, too.</h2></div><div><p class="lead">Good glass work does not need a loud introduction. Its value is visible in how it aligns with the architecture, supports daily use, and holds up as part of the property.</p><p>Master Glass Solutions approaches commercial and residential glass needs with more than 20 years of experience as a foundation. That means listening for the actual project need—whether it is a storefront, a shower enclosure, a custom feature, a window glass issue, or urgent broken glass—then helping the customer move toward the right next step.</p></div></div></section>
<section class="section section-cream values"><div class="shell"><div class="section-heading">{eyebrow("WHAT THE NAME STANDS FOR")}<h2>Craftsmanship without the contractor cliché.</h2></div><div class="value-grid"><article><span>01</span><h3>Precision</h3><p>The opening, the glass, the hardware, and the surrounding surfaces deserve attention to the details people notice.</p></article><article><span>02</span><h3>Reliability</h3><p>Customers need a team that understands the purpose of the work and respects the importance of a clear next step.</p></article><article><span>03</span><h3>Quality</h3><p>The result should serve the property, the people who use it, and the standard the customer wants to uphold.</p></article></div></div></section>
<section class="section location-section"><div class="shell location-grid"><div class="location-card"><p class="card-kicker">LOCAL HOME BASE</p><h2>Boerne, Texas</h2><address>{ADDRESS}</address><a class="text-link" href="contact.html">Get directions & contact details {icon("arrow")}</a></div><div>{eyebrow("LOCAL AUTHORITY")}<h2>Rooted in the needs of Boerne and San Antonio properties.</h2><p>Local relevance should be earned with specific, useful service information—not a long list of unverified city names. This site keeps the service-area focus clear and builds dedicated, helpful pages around confirmed locations.</p><a class="text-link" href="service-areas.html">Explore service areas {icon("arrow")}</a></div></div></section>
{faq_section(faqs,"Straight answers about Master Glass Solutions.")}{mini_cta()}'''
    return layout("About Master Glass Solutions | Boerne & San Antonio Glass Experts","Learn about Master Glass Solutions, a commercial and residential glass installation and fabrication company serving Boerne and San Antonio, Texas.","about.html",body,"",[("About","about.html")],None,faqs)

def contact_page():
    body=f'''{inner_hero("CONTACT MASTER GLASS SOLUTIONS","Let’s start with the right conversation.","For planned residential or commercial glass work, send the project details through the quote form. For a broken glass emergency, call the 24/7 support line.","hero-storefront.jpg",cta_quote()+cta_call("Call {PHONE_DISPLAY}","btn btn-ghost"))}
<section class="section contact-section"><div class="shell contact-grid"><div class="contact-details">{eyebrow("DIRECT CONTACT")}<h2>Call, write, or visit.</h2><a class="contact-row" href="tel:{PHONE_LINK}">{icon("phone")}<span><small>Phone / 24-7 emergency support</small><strong>{PHONE_DISPLAY}</strong></span></a><a class="contact-row" href="mailto:{EMAIL}">{icon("arrow")}<span><small>Email</small><strong>{EMAIL}</strong></span></a><div class="contact-row">{icon("map")}<span><small>Address</small><strong>{ADDRESS}</strong></span></div><p class="contact-note">For any life-safety emergency, call 911 first. For urgent broken-glass support, call Master Glass Solutions directly rather than waiting on a web form.</p></div><div>{quote_form("General project")}</div></div></section>'''
    return layout("Contact Master Glass Solutions | Boerne, TX","Contact Master Glass Solutions in Boerne, TX for residential, commercial, custom, storefront, and emergency glass support.","contact.html",body,"",[("Contact","contact.html")])

def service_areas_page():
    faqs=[("Does Master Glass Solutions serve Boerne, Texas?","Yes. Master Glass Solutions is located in Boerne, Texas at 108 Scheele Rd Unit 4, Boerne, TX 78015."),("Does Master Glass Solutions serve San Antonio, Texas?","San Antonio is presented as a core service area. Send the property location with your project request so the team can discuss the next step."),("How do I know whether my project is within the service area?","Call 210-370-3700 or share the full property location in your quote request. A specific service radius should only be published when the business confirms it.")]
    cities='''<a class="city-card" href="boerne-tx.html"><p>CORE SERVICE AREA</p><h2>Boerne, TX</h2><span>Residential, commercial, custom, storefront, and emergency glass support {icon("arrow")}</span></a><a class="city-card" href="san-antonio-tx.html"><p>CORE SERVICE AREA</p><h2>San Antonio, TX</h2><span>Residential, commercial, custom, storefront, and emergency glass support {icon("arrow")}</span></a>'''
    body=f'''{inner_hero("SERVICE AREAS","Glass services with a clear local focus.","Master Glass Solutions is based in Boerne and presents Boerne and San Antonio as core local service areas for commercial and residential glass work.","hero-storefront.jpg")}
<section class="section areas"><div class="shell"><div class="section-heading centered">{eyebrow("WHERE WE WORK")}<h2>Boerne and San Antonio, Texas.</h2><p>Every service-area page should be useful on its own—answering how the service applies locally rather than repeating the same city name around a generic page.</p></div><div class="city-grid">{cities}</div><div class="service-area-note"><h3>Outside these areas?</h3><p>Do not assume. Send the property address or call <a href="tel:{PHONE_LINK}">{PHONE_DISPLAY}</a> to discuss the project location directly.</p></div></div></section>
{faq_section(faqs,"Service-area questions, answered.")}{mini_cta("Bring the property location into the conversation.","A full address or city helps the team understand the project context and guide the next step.")}'''
    return layout("Glass Services in Boerne & San Antonio, TX | Master Glass Solutions","Master Glass Solutions serves Boerne and San Antonio, Texas with commercial, residential, custom, storefront and emergency glass support.","service-areas.html",body,"Service Areas",[("Service Areas","service-areas.html")],None,faqs)

def city_page(city, filename, local_detail):
    faqs=[(f"Does Master Glass Solutions provide glass services in {city}, TX?",f"{local_detail} Master Glass Solutions provides residential and commercial glass service paths including storefront, custom, shower enclosure, mirror, window glass replacement, and emergency support."),(f"How do I request a glass quote in {city}?",f"Call {PHONE_DISPLAY} or use the quote request form. Include the {city} property address, glass service needed, timing, photos, and approximate dimensions if available."),(f"Is emergency glass support available in {city}?",f"Master Glass Solutions states 24/7 emergency glass support. Call {PHONE_DISPLAY} to explain the damaged opening, location, and immediate safety or security needs.")]
    body=f'''{inner_hero(f"GLASS SERVICES IN {city.upper()}, TX",f"Commercial and residential glass in {city}, with the details in view.",f"{local_detail} Start with the property, the glass need, and the desired result—then choose the service path that fits.","hero-storefront.jpg")}
<section class="section city-context"><div class="shell answer-grid"><div>{eyebrow("LOCAL GLASS EXPERTISE")}<h2>Glass work for {city} properties.</h2></div><div><p class="lead">{local_detail}</p><p>Customers searching locally need a straight answer: what service is available, what information to provide, and how to reach a real next step. This page links directly to the residential, commercial, emergency, storefront, and custom-glass information needed to make that decision.</p></div></div></section>
<section class="section section-cream"><div class="shell city-service-grid">{service_card("Residential glass","Shower glass, mirrors, window panes, and custom home details.","residential-glass.html","01")}{service_card("Commercial glass","Storefront, partition, custom, and property-focused glass work.","commercial-glass.html","02")}{service_card("Emergency glass repair","24/7 support for urgent broken-glass situations.","emergency-glass-repair.html","03")}{service_card("Custom glass","Made-for-the-space solutions when standard is not the answer.","custom-glass.html","04")}</div></section>
<section class="section local-answer"><div class="shell split-info"><div>{eyebrow("WHAT TO EXPECT")}<h2>Start with a useful scope.</h2><p>Share the property address, service type, timing, photos, and approximate measurements. That helps turn a local search into a more productive project conversation.</p></div><div>{eyebrow("FOR URGENT DAMAGE")}<h2>Call, don’t wait on a form.</h2><p>If the glass issue affects safety, security, weather protection, or operations, call the 24/7 emergency support line directly.</p><a class="btn btn-alert" href="tel:{PHONE_LINK}">{icon("phone")} Call {PHONE_DISPLAY}</a></div></div></section>
{faq_section(faqs,f"{city} glass service FAQs.")}{mini_cta(f"Need glass work in {city}?",f"Tell us about the property and the project, or call {PHONE_DISPLAY} for urgent glass support.")}'''
    return layout(f"Glass Services in {city}, TX | Master Glass Solutions",f"Residential, commercial, custom, storefront, window, shower and emergency glass service paths for {city}, Texas.",filename,body,"Service Areas",[("Service Areas","service-areas.html"),(f"{city}, TX",filename)],service_schema(f"Glass Services in {city}, TX",f"Commercial and residential glass services in {city}, Texas.",filename),faqs)

def gallery_page():
    body=f'''{inner_hero("PROJECT SHOWCASE","Good glass work earns a closer look.","A future gallery should be a library of real Master Glass Solutions projects: labeled by service, property type, city, and the detail that made the solution work.","commercial-interior.jpg",cta_quote())}
<section class="section gallery-intro"><div class="shell intro-grid"><div>{eyebrow("PROOF SHOULD BE SPECIFIC")}<h2>Show the opening. Show the outcome.</h2></div><div><p class="lead">Project imagery is one of the strongest conversion assets a glass company can publish—when it is authentic, organized, and tied to a clear service.</p><p>This visual prototype uses concept imagery only. Before launch, replace it with consented, high-resolution photographs of completed Master Glass Solutions work. Add a short factual caption, location only if approved, and the service provided.</p></div></div></section>
<section class="section section-cream"><div class="shell"><div class="gallery-grid"><figure class="gallery-large image-commercial"><figcaption><span>Commercial glass</span><b>Interior partitions / real project image needed</b></figcaption></figure><figure class="gallery-tall image-shower"><figcaption><span>Residential glass</span><b>Custom shower enclosure / real project image needed</b></figcaption></figure><figure class="gallery-wide image-storefront"><figcaption><span>Storefront glass</span><b>Customer-facing glazing / real project image needed</b></figcaption></figure><figure class="gallery-wide image-emergency"><figcaption><span>Emergency repair</span><b>Securing an opening / real project image needed</b></figcaption></figure></div></div></section>
<section class="section gallery-how"><div class="shell split-info"><div>{eyebrow("GALLERY SEO CHECKLIST")}<h2>Turn images into local proof.</h2></div><div><ul class="check-list"><li>{icon("check")}Use original project photos, not vendor or stock imagery.</li><li>{icon("check")}Name files descriptively, such as <em>boerne-frameless-shower-enclosure-master-glass.jpg</em>.</li><li>{icon("check")}Caption each image with the service and project context.</li><li>{icon("check")}Link project sets to the related service and city pages.</li></ul></div></div></section>{mini_cta("Ready to see what your own project could become?","The right next step is a conversation about the actual opening, property, and goal.")}'''
    return layout("Glass Project Showcase | Master Glass Solutions","Explore the Master Glass Solutions approach to residential, commercial, storefront, custom and emergency glass project work.","gallery.html",body,"Projects",[("Project Showcase","gallery.html")])

def reviews_page():
    body=f'''{inner_hero("REVIEWS & TESTIMONIALS","Trust should be sourced, not scripted.","Master Glass Solutions should make room for specific, verified customer feedback about the experience of working together—without padding the page with anonymous or invented endorsements.","residential-shower.jpg")}
<section class="section review-standards"><div class="shell answer-grid"><div>{eyebrow("THE PROOF STANDARD")}<h2>Publish feedback people can actually trust.</h2></div><div><p class="lead">No review quotes were supplied for this rebuild. Rather than fabricate them, this page is prepared to receive a verified Google Business Profile feed and client-approved case-study testimonials.</p><p>Once available, each testimonial should identify its public source or approval status, retain the customer’s wording faithfully, and link to the original review source where possible. Use aggregate rating/review schema only when it matches visible, verifiable reviews.</p></div></div></section>
<section class="section section-cream review-module"><div class="shell"><div class="review-empty"><span class="proof-symbol">“</span><h2>Connect verified reviews before launch.</h2><p>Recommended implementation: a live Google review widget or a manually curated selection of published reviews, with reviewer name/initial, date, source, service context, and link to the original when permitted.</p><a class="btn btn-dark" href="contact.html">Share feedback with the team {icon("arrow")}</a></div></div></section>
<section class="section review-guidance"><div class="shell value-grid"><article><span>01</span><h3>Specific beats generic</h3><p>Feature feedback that mentions communication, a particular glass service, responsiveness, or craftsmanship.</p></article><article><span>02</span><h3>Source it clearly</h3><p>Use “Google review,” “client-approved testimonial,” or a transparent equivalent beside each quote.</p></article><article><span>03</span><h3>Keep it current</h3><p>Rotate in recent reviews while retaining a small archive of detailed, high-value project stories.</p></article></div></section>{mini_cta()}'''
    return layout("Reviews & Testimonials | Master Glass Solutions","Read verified customer feedback and learn how Master Glass Solutions approaches transparent review publishing.","reviews.html",body,"",[("Reviews","reviews.html")])

def faq_page():
    faqs = HOME_FAQS + SERVICE_DATA["residential-glass.html"]["faqs"][:1]+SERVICE_DATA["commercial-glass.html"]["faqs"][:1]+SERVICE_DATA["storefront-glass.html"]["faqs"][:1]+[("Where is Master Glass Solutions located?",f"Master Glass Solutions is located at {ADDRESS}."),("Which cities are core service areas?","Boerne and San Antonio, Texas are the service-area signals currently presented. Call or submit the property location to confirm a particular project.")]
    body=f'''{inner_hero("FREQUENTLY ASKED QUESTIONS","Answers before the estimate conversation.","Quick, direct information about residential, commercial, emergency, storefront, custom, shower, mirror, and window glass service paths in Boerne and San Antonio.","hero-storefront.jpg")}
{faq_section(faqs,"Master Glass Solutions FAQs.","For a specific property, photo, schedule, or glass condition, call or request a quote so the team can move beyond the general answer.")}{mini_cta()}'''
    return layout("Glass Service FAQs | Master Glass Solutions","Direct answers to common commercial, residential, emergency, storefront and custom glass questions in Boerne and San Antonio, TX.","faq.html",body,"",[("FAQ","faq.html")],None,faqs)

def resources_page():
    cards=[("What to do when storefront glass breaks","A safety-first, business-focused emergency checklist.","Emergency glass repair","emergency-glass-repair.html"),("How to plan a frameless shower enclosure","The questions that matter before selecting a configuration.","Shower enclosures","shower-enclosures.html"),("What affects a storefront glass estimate?","Scope, access, system choices, and why details matter.","Storefront glass","storefront-glass.html"),("Window glass replacement: what to document","Photos and information that help make the first conversation useful.","Window glass replacement","window-glass-replacement.html")]
    articles="".join(f'<a class="article-card" href="{link}"><p>{tag}</p><h3>{title}</h3><span>{desc}</span><b>Read the service guide {icon("arrow")}</b></a>' for title,desc,tag,link in cards)
    body=f'''{inner_hero("GLASS RESOURCE CENTER","Useful answers for better glass decisions.","A content hub should demonstrate real local expertise before a customer needs an estimate—not collect thin blog posts around keywords.","commercial-interior.jpg")}
<section class="section resources"><div class="shell"><div class="section-heading">{eyebrow("START HERE")}<h2>Practical guidance, connected to the service.</h2><p>Every resource should answer a customer question, link to its supporting service page, and give readers a clear next step.</p></div><div class="article-grid">{articles}</div></div></section>
<section class="section section-cream content-roadmap"><div class="shell split-info"><div>{eyebrow("EDITORIAL ROADMAP")}<h2>Publish what customers actually ask.</h2></div><div><ul class="check-list"><li>{icon("check")}Emergency storefront glass checklist for Boerne and San Antonio property teams</li><li>{icon("check")}Frameless shower enclosure planning guide for remodels</li><li>{icon("check")}Commercial glass maintenance and damage documentation guide</li><li>{icon("check")}Custom mirror sizing and installation-planning guide</li></ul></div></div></section>{mini_cta()}'''
    return layout("Glass Resources | Master Glass Solutions","Helpful commercial and residential glass guides from Master Glass Solutions in Boerne and San Antonio, Texas.","resources.html",body,"",[("Resources","resources.html")])

def thank_you_page():
    body=f'''<section class="thank-you"><div class="shell thank-you-card"><p class="eyebrow"><span></span>REQUEST RECEIVED</p><h1>Thank you. Your project details are on their way.</h1><p>For a planned project, the next step is a team review of your request. If you have an urgent broken-glass situation, do not wait for a form response—call the 24/7 emergency support line now.</p><div class="hero-actions"><a class="btn btn-dark" href="tel:{PHONE_LINK}">{icon("phone")} Call {PHONE_DISPLAY}</a><a class="btn btn-outline" href="index.html">Return home {icon("arrow")}</a></div><div class="thank-you-next"><span>While you wait</span><a href="gallery.html">Explore project examples {icon("arrow")}</a><a href="faq.html">Read common questions {icon("arrow")}</a></div></div></section>'''
    return layout("Thank You | Master Glass Solutions","Your Master Glass Solutions request has been received.","thank-you.html",body,"",[("Thank You","thank-you.html")],None,None,True)

def emergency_landing():
    faqs=SERVICE_DATA["emergency-glass-repair.html"]["faqs"]
    body=f'''<section class="emergency-landing"><div class="emergency-image" role="img" aria-label="Commercial glass opening secured after hours"></div><div class="shell emergency-landing-grid"><div>{eyebrow("24/7 EMERGENCY GLASS SUPPORT • BOERNE + SAN ANTONIO")}<h1>Secure the opening. Then solve the glass problem.</h1><p>For broken or compromised glass that affects safety, security, weather protection, or business operations, call now and tell us what happened.</p><a class="btn btn-alert btn-large" href="tel:{PHONE_LINK}">{icon("phone")} Call {PHONE_DISPLAY} now</a><p class="urgent-note">For life-safety emergencies, call 911 first. Do not wait for a web-form response.</p></div><aside class="emergency-checklist"><p>Before you call, if safe:</p><ol><li><span>01</span>Keep people clear of broken or loose glass.</li><li><span>02</span>Note the property address and type of opening.</li><li><span>03</span>Take a photo from a safe distance.</li><li><span>04</span>Tell us if the opening is exposed or unsecured.</li></ol></aside></div></section>
<section class="section emergency-after"><div class="shell answer-grid"><div>{eyebrow("WHAT TO EXPECT")}<h2>Start with the immediate condition.</h2></div><div><p class="lead">The first conversation should establish the location, safety concern, type of glass opening, whether it is currently secure, and what needs to happen next.</p><p>Emergency service cost and response conditions depend on the situation. The most useful action is a direct call with clear, factual details.</p></div></div></section>{faq_section(faqs,"Emergency glass questions, answered.")}'''
    return layout("Emergency Glass Repair | Call 210-370-3700 | Master Glass Solutions","Call Master Glass Solutions for 24/7 emergency glass support in Boerne and San Antonio, Texas.","emergency.html",body,"Emergency",[("Emergency Glass Repair","emergency.html")],service_schema("Emergency Glass Repair","24/7 emergency glass support in Boerne and San Antonio, TX.","emergency.html"),faqs)

def quote_process_page():
    faqs=[("How do I request a glass quote?","Use the quote form or call 210-370-3700. Include the property location, glass service, timing, photos, and approximate dimensions if known."),("What details make a quote request more useful?","The most helpful details are the property address, project type, photos, rough measurements, desired timing, existing conditions, and a direct contact for the decision-maker."),("Should I use the quote form for emergency glass damage?","No. For urgent broken glass affecting safety, security, weather protection, or operations, call 210-370-3700 directly for 24/7 emergency support.")]
    body=f'''{inner_hero("THE QUOTE PROCESS","A better estimate begins before the numbers.","A useful glass quote starts with useful project context. Master Glass Solutions makes it easy to share the details that shape the right conversation for a home, business, storefront, or custom glass project.","commercial-interior.jpg")}
<section class="section process"><div class="shell"><div class="section-heading centered">{eyebrow("WHAT TO EXPECT")}<h2>Four steps toward a more precise project conversation.</h2></div><ol class="process-grid"><li><span>01</span><h3>Describe the property</h3><p>Start with the address or city, whether it is a home or business, and the actual glass opening or project.</p></li><li><span>02</span><h3>Send visual context</h3><p>Photos, plans, and rough dimensions help turn a general request into a more informed conversation.</p></li><li><span>03</span><h3>Share the timing</h3><p>Let us know whether this is urgent, active construction, a renovation plan, or early research.</p></li><li><span>04</span><h3>Choose the next step</h3><p>The appropriate path depends on the scope. Emergency damage should always begin with a phone call.</p></li></ol></div></section>
<section class="section section-cream"><div class="shell split-info"><div>{eyebrow("ESTIMATE-READY CHECKLIST")}<h2>Bring these details, if you have them.</h2></div><div><ul class="check-list"><li>{icon("check")}Property address, city, and best point of contact</li><li>{icon("check")}Service need: residential, commercial, storefront, custom, shower, mirror, window, or repair</li><li>{icon("check")}Photos, plans, rough dimensions, or a short walkthrough video</li><li>{icon("check")}Desired result, preferred timing, and any access or scheduling constraints</li></ul></div></div></section>
{faq_section(faqs,"Quote-process questions, answered.")}{mini_cta("Ready to make the first message count?","Send the project context we need to guide a productive next step.")}'''
    return layout("Glass Quote Process | Master Glass Solutions","Learn what to expect when requesting a residential or commercial glass quote from Master Glass Solutions in Boerne and San Antonio, TX.","quote-process.html",body,"",[("Quote Process","quote-process.html")],None,faqs)

def planning_guide_page():
    body=f'''{inner_hero("GLASS PROJECT PLANNING GUIDE","Before you request glass, get the details in view.","A concise, practical checklist for homeowners, business owners, and property teams planning a residential or commercial glass project in Boerne or San Antonio.","residential-shower.jpg",cta_quote("Request your project quote", "btn btn-light"))}
<section class="section guide-intro"><div class="shell intro-grid"><div>{eyebrow("A BETTER FIRST CONVERSATION")}<h2>The free planning checklist.</h2></div><div class="intro-copy"><p class="lead">Do not guess your way into a glass project. Gather the details that make it easier to explain the opening, compare options, and ask the right questions.</p><p>This lead magnet is intentionally useful, not a generic sales download. It gives potential clients a clean planning framework while positioning Master Glass Solutions as the expert guide.</p></div></div></section>
<section class="section section-cream"><div class="shell quote-layout"><div><div class="guide-list"><p class="card-kicker">WHAT’S INSIDE</p><h2>What to document before you call.</h2><ol class="compact-steps"><li><span>01</span><div><h3>Opening + condition</h3><p>Capture the width, height, surrounding surfaces, existing damage, and door or window function.</p></div></li><li><span>02</span><div><h3>Visual direction</h3><p>Save a few references and note the look, privacy, hardware, or use needs you care about.</p></div></li><li><span>03</span><div><h3>Project constraints</h3><p>Write down timing, access, occupancy, business operations, and any renovation dependencies.</p></div></li><li><span>04</span><div><h3>Questions for the glass team</h3><p>Use a short prompt list so every estimate conversation begins with clarity.</p></div></li></ol></div></div><div><form class="lead-form" action="thank-you.html" method="get" data-lead-form><div class="form-title"><span>FREE</span><div><h2>Get the checklist</h2><p>Have the guide sent to your inbox once a CRM/email platform is connected.</p></div></div><div class="form-grid"><label>First name <b>*</b><input required name="first-name" autocomplete="given-name"></label><label>Email <b>*</b><input required name="email" type="email" autocomplete="email"></label><label>Project type <select name="service"><option>Residential glass</option><option>Commercial glass</option><option>Still planning</option></select></label><label>City <input name="location" placeholder="Boerne or San Antonio"></label><label class="checkbox full"><input required type="checkbox" name="consent"><span>I agree that Master Glass Solutions may send the planning guide and related project information. <b>*</b></span></label></div><button class="btn btn-dark form-submit" type="submit">Send me the checklist {icon("arrow")}</button><p class="form-note">Before launch: connect this form to a consent-based email platform and attach the final branded PDF checklist.</p></form></div></div></section>{mini_cta("Have a project in mind already?","Skip the guide and send the details of the opening directly.")}'''
    return layout("Free Glass Project Planning Checklist | Master Glass Solutions","Download the planning checklist for a residential or commercial glass project in Boerne or San Antonio, Texas.","glass-project-planning-checklist.html",body,"",[("Glass Project Planning Checklist","glass-project-planning-checklist.html")])

def write(filename, html):
    (OUT / filename).write_text(html,encoding="utf-8")

write("index.html",layout("Master Glass Solutions | Commercial & Residential Glass in Boerne & San Antonio, TX","Premium commercial and residential glass installation, fabrication, storefront, custom glass, and 24/7 emergency support in Boerne and San Antonio, TX.","index.html",home(),"",None,None,HOME_FAQS))
for f,d in SERVICE_DATA.items(): write(f,service_page(f,d))
write("about.html",about_page())
write("contact.html",contact_page())
write("service-areas.html",service_areas_page())
write("boerne-tx.html",city_page("Boerne","boerne-tx.html","Master Glass Solutions is based in Boerne, Texas and provides a local starting point for commercial and residential glass installation, fabrication, custom glass, storefront work, and emergency glass support."))
write("san-antonio-tx.html",city_page("San Antonio","san-antonio-tx.html","San Antonio is a core service-area signal for Master Glass Solutions. Commercial and residential customers can start with the glass need, the property context, and a clear request for the next step."))
write("gallery.html",gallery_page())
write("reviews.html",reviews_page())
write("faq.html",faq_page())
write("resources.html",resources_page())
write("request-quote.html",quote_page("request-quote.html","General project","Start with the details that make a quote more useful.","Tell us about the property, service, timing, and what you are trying to accomplish. For an urgent broken-glass situation, call instead of submitting this form.","REQUEST A GLASS QUOTE"))
write("residential-quote.html",quote_page("residential-quote.html","Residential project","A considered glass project starts with your home.","Share the space, your project goal, photos or rough dimensions, and the timing you have in mind. We’ll route your request as a residential glass project.","RESIDENTIAL GLASS QUOTE"))
write("commercial-quote.html",quote_page("commercial-quote.html","Commercial project","Make the commercial glass conversation more productive from the first message.","Include property, project, access, schedule, plan, and decision-maker details where possible. For urgent damage, call the emergency line.","COMMERCIAL PROJECT ESTIMATE"))
write("emergency.html",emergency_landing())
write("quote-process.html",quote_process_page())
write("glass-project-planning-checklist.html",planning_guide_page())
write("thank-you.html",thank_you_page())
print("Built", len(list(OUT.glob('*.html'))), "HTML pages")
